library(tidyverse)

read_csv(
  "data_generated/assets.csv",  # file generated by website preprocessing script
  col_names = c("server", "gh")
) %>%
  filter(!str_detect(gh, "werner-collected|eybler-sacred|tuma-collected|haydn-m-proprium")) %>%
  separate_wider_regex(server, c(".*assets/", repo = ".+", "/.*pdf")) %>%
  distinct(repo) %>%
  mutate(cmd = str_glue("gh release download -R edition-esser-skala/{repo} -D {repo} -p '*.pdf' -p '*.midi'")) %>%
  pull(cmd) %>%
  write_lines("run.sh")
